######################################################################
##
## Filename: pri_encoder_4_1.udo
## Created on: Fri Feb 01 7:35:35 PM Eastern Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
