######################################################################
##
## Filename: pri_encoder_4_1_vtf.udo
## Created on: Fri Feb 01 6:48:17 PM Eastern Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
