######################################################################
##
## Filename: bfa_gate_vtf.udo
## Created on: Fri Feb 01 12:24:06 AM Eastern Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
