######################################################################
##
## Filename: nbit_pc_vtf.udo
## Created on: Sat Feb 23 3:55:11 PM Eastern Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
