######################################################################
##
## Filename: alu_bitslice.udo
## Created on: Tue Feb 12 11:08:55 PM Eastern Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
