######################################################################
##
## Filename: alu_nbit_vtf.udo
## Created on: Wed Apr 17 5:31:28 PM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
