######################################################################
##
## Filename: alu_nbit.udo
## Created on: Wed Apr 17 5:33:46 PM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
