######################################################################
##
## Filename: n_bit_alu_generate_vtf.udo
## Created on: Tue Feb 12 8:46:41 PM Eastern Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
