######################################################################
##
## Filename: alu_nbit.udo
## Created on: Sun Apr 21 5:01:49 PM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
