######################################################################
##
## Filename: iramITR.udo
## Created on: Tue Apr 23 2:19:59 AM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
