######################################################################
##
## Filename: LdStr_shifter.udo
## Created on: Sat Apr 20 1:42:53 PM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
