######################################################################
##
## Filename: mux_4_1.udo
## Created on: Sat Apr 20 2:43:37 PM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
