######################################################################
##
## Filename: processor_test.udo
## Created on: Fri Apr 19 7:30:38 PM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
