######################################################################
##
## Filename: dff_syn_low_clr_set.udo
## Created on: Wed Mar 27 1:24:14 AM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
