######################################################################
##
## Filename: pri_encoder_4_2.udo
## Created on: Wed Mar 27 12:42:48 AM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
