######################################################################
##
## Filename: mux_4_1_behavioral_vtf.udo
## Created on: Tue Jan 29 5:39:56 PM Eastern Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
