######################################################################
##
## Filename: ld_st_shift_nbit_vtf.udo
## Created on: Mon Feb 18 7:12:49 PM Eastern Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
