######################################################################
##
## Filename: alu_bitslice_vtf.udo
## Created on: Tue Feb 05 7:42:01 PM Eastern Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
