######################################################################
##
## Filename: ld_st_rg_struct_generate_vtf.udo
## Created on: Fri Feb 15 1:43:57 AM Eastern Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
