######################################################################
##
## Filename: DFlop_clk_SR_vtf.udo
## Created on: Wed Feb 13 1:00:24 AM Eastern Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
